# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='user_items',
            new_name='wishItems',
        ),
        migrations.RemoveField(
            model_name='item',
            name='author',
        ),
        migrations.AlterField(
            model_name='item',
            name='content',
            field=models.CharField(max_length=255),
        ),
    ]
